#!/usr/bin/env bash

export EASY_RSA="/etc/openvpn/easyrsa"
export OPENSSL="openssl"
export PKCS11TOOL="pkcs11-tool"
export GREP="grep"

export KEY_CONFIG=`$EASY_RSA/openssl.cnf`
export KEY_DIR="/etc/openvpn/pki"
export PKCS11_MODULE_PATH="dummy"
export PKCS11_PIN="dummy"
export KEY_SIZE=2048
export CA_EXPIRE=3650
export KEY_EXPIRE=3650

export KEY_COUNTRY="RU"
export KEY_PROVINCE="Moscow"
export KEY_CITY="Moscow"
export KEY_ORG="nonameFFh"
export KEY_EMAIL="noname.ffh@gmail.com"
export KEY_OU="Community"
export KEY_NAME="connect.nonameffh.pw"
export KEY_CN="connect.nonameffh.pw"

